### ISSUE TITLE
Connection closed by pool

### ISSUE THREAD

**Issue by cristianvsl** [NeoxaChain/kawpow-pool#13]
Hello,

I have managed to setup neoxa pool. Everything looking good except i get connection closed by pool when trying to connect miner to the pool on port 10001 or any other ports to 10008.
It connects for few seconds, even pass dag verification but then it closes the connection.

What i am doing wrong?

**Comment by dogemackenzie** [comment]
You got further than I did. Did you have to recomplile? I got errors when installing

**Comment by cristianvsl** [comment]
> You got further than I did. Did you have to recomplile? I got errors when installing

Got it to work. Check it out http://neoxa.mining-pub.com
I also have ETC pool https://etc.mining-pub.com
Contact me on email if you'd like to set it up correctly both NODE and POOL.
dmk.st01@outlook.com
