### ISSUE TITLE
High effort shown

### ISSUE THREAD

**Issue by mueller-webservice** [NeoxaChain/kawpow-pool#17]
The effort in the "payments" page shows a unrealisticly high value. I found the snippet, where the calculation is made:

https://github.com/NeoxaChain/kawpow-pool/blob/cd1b14a64933e2151fcd0e1aebd45591add0d14c/website/pages/blocks.html#L215

Could it be, that this calculation is totally wrong? "Shares * 100" does not seem like the correct calculation. Anyone having the same issue?

**Comment by AlphaX-Projects** [comment]
This take over from old source
