### ISSUE TITLE
 My friend and I want to build a pool SOLO

### ISSUE THREAD

**Issue by caodaye** [NeoxaChain/kawpow-pool#4]
My friend and I wanted to build a pool by SOLO, but we couldn't build it, or we couldn't connect after it was built. The ports of the VPS were all open.

**Comment by cristianvsl** [comment]
I can help. https://neoxa.mining-pub.com

Project is for sale along with $100 free Credit on digitalocean for 90 days after that is $50 or so per month for each 4core/8gb ram droplet on NVME storage.

See also https://etc.mining-pub.com with a completely redone frontend.

Cheers
